In [331]:
import nltk 
from os import getcwd
import numpy as np
import pandas as pd
from nltk.corpus import twitter_samples
from utils import *

In [332]:
all_postive_tweets=twitter_samples.strings("positive_tweets.json")
all_negative_tweets=twitter_samples.strings("negative_tweets.json")

In [333]:
pos_train=all_postive_tweets[:4000]
pos_test=all_postive_tweets[4000:]
neg_train=all_negative_tweets[:4000]
neg_test=all_negative_tweets[4000:]
x_train=pos_train+neg_train
test_x=pos_test+neg_test

In [334]:
#create label
y_train=np.append(np.ones((len(pos_train),1)), np.zeros((len(neg_train),1)),axis=0)
test_y=np.append(np.ones((len(pos_test),1)),np.zeros((len(neg_test),1)),axis=0)

In [335]:
print(y_train,test_y)
print(test_y.shape)
print(y_train.shape)

[[1.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]] [[1.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]]
(2000, 1)
(8000, 1)


In [336]:
# build the dicts
freqs=build_freqs(x_train,y_train)
print(len(freqs))
print(type(freqs))

11427
<class 'dict'>


In [337]:
freqs

{('followfriday', 1.0): 23,
 ('top', 1.0): 30,
 ('engag', 1.0): 7,
 ('member', 1.0): 14,
 ('commun', 1.0): 27,
 ('week', 1.0): 72,
 (':)', 1.0): 2960,
 ('hey', 1.0): 60,
 ('jame', 1.0): 7,
 ('odd', 1.0): 2,
 (':/', 1.0): 5,
 ('pleas', 1.0): 81,
 ('call', 1.0): 27,
 ('contact', 1.0): 4,
 ('centr', 1.0): 1,
 ('02392441234', 1.0): 1,
 ('abl', 1.0): 6,
 ('assist', 1.0): 1,
 ('mani', 1.0): 28,
 ('thank', 1.0): 522,
 ('listen', 1.0): 15,
 ('last', 1.0): 39,
 ('night', 1.0): 55,
 ('bleed', 1.0): 2,
 ('amaz', 1.0): 41,
 ('track', 1.0): 5,
 ('scotland', 1.0): 2,
 ('congrat', 1.0): 15,
 ('yeaaah', 1.0): 1,
 ('yipppi', 1.0): 1,
 ('accnt', 1.0): 2,
 ('verifi', 1.0): 2,
 ('rqst', 1.0): 1,
 ('succeed', 1.0): 1,
 ('got', 1.0): 57,
 ('blue', 1.0): 8,
 ('tick', 1.0): 1,
 ('mark', 1.0): 1,
 ('fb', 1.0): 4,
 ('profil', 1.0): 2,
 ('15', 1.0): 4,
 ('day', 1.0): 187,
 ('one', 1.0): 92,
 ('irresist', 1.0): 2,
 ('flipkartfashionfriday', 1.0): 16,
 ('like', 1.0): 187,
 ('keep', 1.0): 55,
 ('love', 1.0): 336,
 

In [338]:
# processed tweet example
print(test_x[10])
process_tweet(test_x[10])

:3 !   Good nigth :): estoy escuchando a Enemy of God


['3', 'good', 'nigth', ':)', 'estoy', 'escuchando', 'enemi', 'god']

$$ h(z) = \frac{1}{1+\exp^{-z}} \tag{1}$$

In [339]:
# logistic regression
def sigmoid(z):
    h=1/(1+np.exp(-1*z))
    return h


In [340]:
import logistic_test
logistic_test.test_sigmoid(sigmoid)

 All tests passed


$$z = \theta_0 x_0 + \theta_1 x_1 + \theta_2 x_2 + ... \theta_N x_N$$
$$ h(z) = \frac{1}{1+\exp^{-z}}$$
$$J(\theta) = -\frac{1}{m} \sum_{i=1}^m y^{(i)}\log (h(z(\theta)^{(i)})) + (1-y^{(i)})\log (1-h(z(\theta)^{(i)}))\tag{5} $$
$$ Loss = -1 \times \left( y^{(i)}\log (h(z(\theta)^{(i)})) + (1-y^{(i)})\log (1-h(z(\theta)^{(i)})) \right)$$
$$\nabla_{\theta_j}J(\theta) = \frac{1}{m} \sum_{i=1}^m(h^{(i)}-y^{(i)})x^{(i)}_j \tag{5}$$
$$\theta_j = \theta_j - \alpha \times \nabla_{\theta_j}J(\theta) $$


In [341]:
def gradinet_descent(x,y,theta,alpha,num_iters):
    m=len(y)
    for i in range(0,num_iters):
        z=np.matmul(x,theta)
        h=sigmoid(z)
        J = -1/m * (np.squeeze(np.matmul(y.T , np.log(h))) + np.squeeze(np.matmul((1 - y).T , np.log(1-h))))
        theta = theta - alpha / m * np.squeeze(np.matmul(x.T,(h-y)))[:,np.newaxis]
    J = float(J)
    return J, theta

In [342]:
# temp example
np.random.seed(1)
temp_x=np.append(np.ones((10,1)),np.random.rand(10,2)*2000,axis=1)
temp_y=(np.random.rand(10, 1) > 0.35).astype(float)
temp_J,temp_theta=gradinet_descent(temp_x,temp_y,np.zeros((3,1)),1e-8,700)
print(temp_J,temp_theta)
for t in np.squeeze(temp_theta):
    print(f"{[(round(t,8))]}")

0.6709497038162118 [[4.10713435e-07]
 [3.56584699e-04]
 [7.30888526e-05]]
[4.1e-07]
[0.00035658]
[7.309e-05]


In [343]:
## test gradient descent
logistic_test.test_gradientDescent(gradinet_descent)

 All tests passed


In [344]:
freqs.get(("abl",1),0)

6

In [345]:
def extract_features(tweet,freqs,process_tweet=process_tweet):
    list_word=process_tweet(tweet)
    x=np.zeros((1,3))
    x[0,0]=1 #bais
    for word in list_word:
        x[0,1]+=freqs.get((word,1),0)
        x[0,2]+=freqs.get((word,0),0)
    assert(x.shape == (1, 3))
    return x

In [346]:
# example
print(extract_features(x_train[0],freqs))
print(extract_features('going to be streaming soon :)', freqs))

[[1.000e+00 3.133e+03 6.100e+01]]
[[1.000e+00 3.133e+03 2.450e+02]]


In [347]:
logistic_test.test_extract_features(extract_features,freqs)

 All tests passed


In [348]:
#train the model
X=np.zeros((len(x_train),3))
for i in range(len(x_train)):
    X[i,:]=extract_features(x_train[i],freqs)
Y=y_train
J,theta=gradinet_descent(X,Y, np.zeros((3, 1)), 1e-9, 1500)
print(J,theta)

0.22521264220565082 [[ 6.03424369e-08]
 [ 5.38195957e-04]
 [-5.58303150e-04]]


In [349]:
#  test
def predict_tweet(tweet,freqs,theta):
    x=extract_features(tweet,freqs)
    y_pred=sigmoid(np.dot(x,theta))
    return y_pred

In [350]:
#example
for tweet in ['I am happy', 'I am bad', 'this movie should have been great.', 'great', 'great great', 'great great great', 'great great great great']:
    print( '%s -> %f' % (tweet, predict_tweet(tweet, freqs, theta)))    

I am happy -> 0.519275
I am bad -> 0.494347
this movie should have been great. -> 0.515980
great -> 0.516065
great great -> 0.532097
great great great -> 0.548063
great great great great -> 0.563930


/tmp/ipykernel_78554/1565636787.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print( '%s -> %f' % (tweet, predict_tweet(tweet, freqs, theta)))


In [351]:
def test_logisitic_regression(test_x,test_y,freqs,theta,predict_tweet=predict_tweet):
    m=len(test_y)
    yhat=[]
    for tweet in test_x:
        y_pred=predict_tweet(tweet,freqs,theta)
        if y_pred>0.5:
            yhat.append(1.0)
        else:
            yhat.append(0.0)
    yhat=np.array(yhat)[:,np.newaxis]
    accuracy=np.sum(yhat==test_y)/m
    return accuracy

In [352]:
#test accuracy
test_accuracy = test_logisitic_regression(test_x, test_y, freqs, theta)
test_accuracy

0.995

In [353]:
logistic_test.unittest_test_logistic_regression(test_logisitic_regression,freqs,theta)

 All tests passed


In [362]:
# error analysis
#tweets the model missclassifies 
for x,y in zip(test_x,test_y):
    yhat=predict_tweet(x,freqs,theta) 
    if  np.abs(y-(yhat>0.5))>0:
        print(f"tweet: {x}")
        print(f"processed tweet: {process_tweet(x)}")
        print(f"y vs yhat: {y} {yhat}")

tweet: @MarkBreech Not sure it would be good thing 4 my bottom daring 2 say 2 Miss B but Im gonna be so stubborn on mouth soaping ! #NotHavingit :p
processed tweet: ['sure', 'would', 'good', 'thing', '4', 'bottom', 'dare', '2', 'say', '2', 'miss', 'b', 'im', 'gonna', 'stubborn', 'mouth', 'soap', 'nothavingit', ':p']
y vs yhat: [1.] [[0.48942981]]
tweet: I'm playing Brain Dots : ) #BrainDots
http://t.co/UGQzOx0huu
processed tweet: ["i'm", 'play', 'brain', 'dot', 'braindot']
y vs yhat: [1.] [[0.48418981]]
tweet: I'm playing Brain Dots : ) #BrainDots http://t.co/aOKldo3GMj http://t.co/xWCM9qyRG5
processed tweet: ["i'm", 'play', 'brain', 'dot', 'braindot']
y vs yhat: [1.] [[0.48418981]]
tweet: I'm playing Brain Dots : ) #BrainDots http://t.co/R2JBO8iNww http://t.co/ow5BBwdEMY
processed tweet: ["i'm", 'play', 'brain', 'dot', 'braindot']
y vs yhat: [1.] [[0.48418981]]
tweet: off to the park to get some sunlight : )
processed tweet: ['park', 'get', 'sunlight']
y vs yhat: [1.] [[0.49636406]]
t

In [364]:
# predict personal tweet
temp_tweet="messi is better than ronaldo"
process_tweet(temp_tweet)
temp_yhat=predict_tweet(temp_tweet,freqs,theta)
print(temp_yhat)

[[0.50091555]]
